# Generated by Django 6.0.2 on 2026-03-16 02:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Anotacion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("anotacion", models.TextField()),
                ("fecha", models.DateField(auto_now_add=True)),
                (
                    "alumno",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="alumnos.alumno"
                    ),
                ),
            ],
        ),
    ]
