# Generated by Django 6.0.2 on 2026-03-20 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("alumnos", "0002_anotacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alumno",
            name="apellido",
            field=models.CharField(max_length=100, verbose_name="Apellido"),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="correo_electronico",
            field=models.EmailField(max_length=254, unique=True, verbose_name="Email"),
        ),
        migrations.AlterField(
            model_name="alumno",
            name="nombre",
            field=models.CharField(max_length=100, verbose_name="Nombre"),
        ),
        migrations.AlterField(
            model_name="anotacion",
            name="anotacion",
            field=models.TextField(verbose_name="Anotacion"),
        ),
        migrations.AlterField(
            model_name="anotacion",
            name="fecha",
            field=models.DateField(auto_now_add=True, verbose_name="Fecha"),
        ),
    ]
