# Generated by Django 6.0.2 on 2026-03-20 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Profesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100, verbose_name="Nombre")),
                ("apellido", models.CharField(max_length=100, verbose_name="Apellido")),
                (
                    "especialidad",
                    models.CharField(max_length=100, verbose_name="Especialidad"),
                ),
                (
                    "correo_electronico",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
            ],
        ),
    ]
