# Generated by Django 6.0.2 on 2026-03-20 03:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profesores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ObservacionProfesor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("observacion", models.TextField(verbose_name="Observacion")),
                ("fecha", models.DateField(auto_now_add=True, verbose_name="Fecha")),
                (
                    "profesor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="profesores.profesor",
                    ),
                ),
            ],
        ),
    ]
